name: crime_game
description: "The crime game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
     - dotenv
  #   - images/a_dot_ham.jpeg
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
